[run]
timeout = "10m"

[linters]
disable-all = true
enable = [
  "errcheck",
  "gofmt",
  "goimports",
  "golint",
  "staticcheck",
  "unused",
]

[issues]
excludeGenerated = false

[linter-settings]
govet = true
