services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: golang_learn
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - mysql

  magnito:
    image: frourio/magnito:latest
    ports:
      - 5050:5050 # Cognito API
      - 5051:5051 # Web interface
      - 5052:5052 # OAuth2 SSL endpoint
    environment:
      COGNITO_USER_POOL_ID: ap-northeast-1_local
      COGNITO_USER_POOL_CLIENT_ID: magnito-client-name
      COGNITO_ACCESS_KEY: magnito-access-key
      COGNITO_SECRET_KEY: magnito-secret-key
      COGNITO_REGION: ap-northeast-1_local
      SMTP_HOST: inbucket
      SMTP_PORT: 2500
      SMTP_USER: fake_mail_user
      SMTP_PASS: fake_mail_password
    volumes:
      - ./magnito/data:/usr/src/app/data
    depends_on:
      - inbucket

  inbucket:
    image: inbucket/inbucket:latest
    ports:
      - 9002:9000 # Web interface
      - 2500:2500 # SMTP
      - 1100:1100 # POP3
    environment:
      INBUCKET_MAILBOXNAMING: full

volumes:
  mysql_data:
