development:
  dialect: mysql
  datasource: root:password@tcp(localhost:3306)/golang_learn?parseTime=true
  dir: migrations
  table: migrations

production:
  dialect: mysql
  datasource: root:password@tcp(mysql:3306)/golang_learn?parseTime=true
  dir: migrations
  table: migrations
